### ISSUE TITLE
OrcaSlicer in Kasm

### ISSUE THREAD

**Issue by bencorkeryhome** [achtnullzwei/kasm-registry#1]
OrcaSlicer downloads correctly into my Kasm Workspace from the admin side, but then shows an error on the user side that says "This Image has not been detected on an Agent. It may still be downloading. Refresh this page to check the status again or contact an Administrator."

**Comment by achtnullzwei** [comment]
Hi. This is only for my personal purposes. The docker registry i am using is not exposed to the internet. 

You should be able to use this one. I think that registry is exposed. https://github.com/michaeljones32/kasm-registry

I will update the readme.
